[package]
name = "control-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8.3"
tokio = "1.26.0"
prost = "0.11.8"
reqwest = { version = "0.11.18", features=["json"] }

[dev-dependencies]
libc = "0.2.140"

[build-dependencies]
tonic-build = "0.8.4"